### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Lorg/apache/http/client/utils/URIBuilder;

### ISSUE THREAD

**Issue by hbmartin** [coinbase/coinbase-java#14]
When I try to implement the example from the coinbase-android-sdk repo, I get the following error:

java.lang.NoClassDefFoundError: Failed resolution of: Lorg/apache/http/client/utils/URIBuilder;
            at com.coinbase.api.CoinbaseImpl.getAuthorizationUri(CoinbaseImpl.java:1127)

How can I fix this?

**Comment by hbmartin** [comment]
Just what I needed, thanks :smile:

**Comment by gundubandagar** [comment]
compile('com.omertron:themoviedbapi:4.2') {
        exclude group: 'org.apache.httpcomponents', module: 'httpclient'
        exclude module: 'junit'
    }
